# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92f611dceeb1d14bcfe3d5809cfd9cb4f6fde69eed8f35abb5a7b98157612ebddb1120702a6044445fad85e293f6b10e3d22fce956bd709844de90686e6603b3

test:
  secret_key_base: 44e99bdc27c7e260286ed75728344e4800656f218a931d48f00a2907a0b3594141461ffa42c1648956519222b73b91a2041f5ebfdefeababf09856239a23392e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
